{% set name = "toyplot" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e7350b7ec5af5dab5c5a74f1a820f03a8c51424144b16411fef5def087a992d4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - arrow
    - custom-inherit
    - multipledispatch
    - numpy >=1.8.0
    - pypng
    - python >=3.6
    - reportlab
    - six

test:
  imports:
    - toyplot
    - toyplot.reportlab

about:
  home: http://toyplot.readthedocs.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE  # Local copy can be removed after https://github.com/sandialabs/toyplot/issues/197
  summary: A modern plotting toolkit supporting electronic publishing and reproducibility.
  dev_url: https://github.com/sandialabs/toyplot

extra:
  recipe-maintainers:
    - dpryan79
