{% set name = "toyplot" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: abdecb0c264e3f695cf560eea16076eee8ef79c900f69edebac7fb0b27fc0c0b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core
  run:
    - python >={{ python_min }}
    - arrow
    - custom-inherit
    - multipledispatch
    - numpy >=1.8.0
    - pypng
    - reportlab
    - six

test:
  requires:
    - python {{ python_min }}
  imports:
    - toyplot
    - toyplot.reportlab

about:
  home: http://toyplot.readthedocs.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE  # Local copy can be removed after https://github.com/sandialabs/toyplot/issues/197
  summary: A modern plotting toolkit supporting electronic publishing and reproducibility.
  dev_url: https://github.com/sandialabs/toyplot

extra:
  recipe-maintainers:
    - dpryan79
    - eaton-lab
